clc;clear;
Vr=230000;
l=100000;
R=1;
L=0.001;
Pr=250000000;
Rt=R*l/1000;
Lt=L*l/1000;
Xl=(2*pi*50*Lt);
Z=Rt-Xl*j;
A=1;
B=Z;
C=0;
D=A;
Ir=(Pr/(Vr*3*0.95))*(0.95-sqrt(1-0.95*0.95)*j);
Vs=A*Vr+B*Ir;
Is=C*Vr+D*Ir;
fprintf("The value of Vs is: \n");
disp(Vs);
disp(abs(Vs));
disp(angle(Vs)*180/pi);
fprintf("The value of Is is: \n");
disp(Is);
disp(abs(Is));
disp(angle(Is)*180/pi);
thetaVs=angle(Vs);
thetaIs=angle(Is);
fprintf("The value of PFs is: \n");
disp(cos((thetaVs-thetaIs)*180/pi));
Ps=3*Vs*Is*cos(thetaVs-thetaIs);
pereff=(abs(Ps)-Pr)*100/abs(Ps);
fprintf("The value of efficiency is: \n");
disp(abs(pereff));
perVR=(abs(Vs)-Vr)*100/abs(Vs);
fprintf("The value of voltage regulation is: \n");
disp(perVR);